name: Docker

on:
  workflow_call:

permissions:
  contents: read

jobs:
  docker:
    runs-on: python-latest
    uses: actions/checkout@v3
    steps:
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v2.5.0
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: eduardorenz
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
