name: Continuous Delivery

on:
  workflow_call:

jobs:
  ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Obtain task file
        run: aws ecs describe-task-definition --task-definition API_Task-Python --query taskDefinition > task-definition.json
