name: Continuous Delivery

on:
  workflow_call:

jobs:
  ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Obtain task file
        run: aws ecs describe-task-definition --task-definition API_Task-Python --query taskDefinition > task-definition.json

      - name: Copy old task-definition
        run: cp task-definition.json task-definition.json.old

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: Python
          image: eduardorenz/python_ci:${{github.run_number}}
          environment-variables: |
            environment='deploy-ECS-github-actions'

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: API_service_Python
          cluster: API-Python
          wait-for-service-stability: true

      - name: Request
        continue-on-error: true
        run: echo "REQUEST=0" >> $GITHUB_ENV ; sleep 30s ; wget http://api-pyhon-lb-848475379.us-east-2.elb.amazonaws.com:5000/ || echo "REQUEST=1" >> $GITHUB_ENV

      - name: RollBack old dask
        if: ${{ env.REQUEST != 0 }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json.old
          service: Servico_API-Go
          cluster: API-Go
          wait-for-service-stability: true
